# Generated by Django 3.2.9 on 2021-11-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vitamin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('company', models.CharField(max_length=255, verbose_name='Фирма')),
                ('rating', models.FloatField(verbose_name='Рейтинг')),
                ('count_feedback', models.IntegerField(verbose_name='Количество отзывов')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('weight', models.IntegerField(verbose_name='Вес')),
                ('is_in_stock', models.BooleanField(verbose_name='В наличии')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка')),
                ('update_time', models.TimeField(verbose_name='Время обновления')),
            ],
        ),
    ]
