# Generated by Django 3.2.9 on 2021-11-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30, verbose_name='Страна')),
                ('type', models.CharField(max_length=30, verbose_name='Тип')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('company', models.CharField(max_length=255, verbose_name='Фирма')),
                ('rating', models.FloatField(verbose_name='Рейтинг')),
                ('count_feedback', models.IntegerField(verbose_name='Количество отзывов')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('weight', models.IntegerField(verbose_name='Вес')),
                ('is_in_stock', models.BooleanField(verbose_name='В наличии')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('min_price', models.IntegerField(verbose_name='Минимальная цена')),
                ('max_price', models.IntegerField(verbose_name='Максимальная цена')),
                ('update_time', models.TimeField(verbose_name='Время обновления')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
            },
        ),
        migrations.DeleteModel(
            name='Vitamin',
        ),
    ]
