# Generated by Django 3.2.9 on 2021-11-13 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211113_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.search'),
        ),
    ]
